version: '3.8'

services:
  bodyvision-prod:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./assets:/app/assets
      # Don't mount source code in production
    environment:
      - DEBUG=false
      - BODYVISION_DEV_MODE=false
    command: ["python", "start_prod.py"]
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
