version: '3.8'

services:
  bodyvision:
    build: .
    ports:
      - "7860:7860"
    volumes:
      - ./logs:/app/logs
      - ./assets:/app/assets
    environment:
      - DEBUG=true
      - DEVICE=cpu
    restart: unless-stopped
